### ISSUE TITLE
Configurar Rubocop + Actions

### ISSUE THREAD

**Issue by maikondouglas** [maikondouglas/send_mailer#2]

**Comment by lucas-carmichael-vindi** [comment]
### Descrição

- Adicionar as configurações definidas em conjunto para o Rubocop.
- Adicionar no CI do GitHub Actions.

**Comment by lucas-carmichael-vindi** [comment]
![evd_1](https://github.com/maikondouglas/send_mailer/assets/128634077/f0c30707-cb37-42f4-bc57-4e461bc86fc5)
